FROM mongo

COPY dump /dump
# CMD echo "before run"
# COPY mongorestore.sh /docker-entrypoint-initdb.d/
# CMD mongorestore --host=localhost:27017 -u admin -p admin --authenticationDatabase admin dump/machinevisor
# CMD echo "tell me that you are runned"
# CMD ls 2>&1